version: "3.9"

services:
  backend:
    build: .
    container_name: shoplite_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      user: postgres.wqjuxtcekltlxpagpqdg
      password: xEG6NfY1QVgUFGpa
      host: aws-1-ap-southeast-1.pooler.supabase.com
      port: 5432
      dbname: postgres


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: shoplite_frontend
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - "3000:80"